name: mmorps
version: '0.1.0.0'
category: Web
author: Kris Jenkins
maintainer: krisajenkins@gmail.com
copyright: 2017 Kris Jenkins
license: BSD3
github: krisajenkins/mmorps
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
    - base >=4.7 && <5
    - servant
    - servant-server
    - lens
    - containers
    - mtl
    - transformers
    - wai
    - wai-cors
    - warp
    - aeson
    - servant-elm
    - uuid
    - time
    - text
    - stm
executables:
  mmorps:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - mmorps
tests:
  mmorps-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - mmorps
